import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const [html, css, game, favicon] = await Promise.all([
  readFile(new URL("../index.html", import.meta.url), "utf8"),
  readFile(new URL("../styles.css", import.meta.url), "utf8"),
  readFile(new URL("../game.js", import.meta.url), "utf8"),
  readFile(new URL("../favicon.svg", import.meta.url), "utf8"),
]);

assert.match(html, /id="gameCanvas"/);
assert.match(html, /game\.js\?v=20260825-cinematic/);
assert.match(html, /styles\.css\?v=20260825-cinematic/);
assert.match(html, /data-weapon="laser"/);
assert.match(html, /data-weapon="missile"/);
assert.match(html, /data-weapon="plasma"/);
assert.match(html, /data-weapon="railgun"/);
assert.match(html, /class="weapon-slot" data-weapon="missile"[^>]*hidden disabled/);
assert.match(html, /id="configPopover"[^>]*hidden/);
assert.match(html, /<kbd>TAB<\/kbd> UPGRADES/);
assert.match(html, /id="gameOverReason"/);
assert.match(html, /href="favicon\.svg"/);
assert.match(html, /id="settingsPopover"[^>]*hidden/);
assert.match(html, /<kbd>O<\/kbd> OPTIONS/);
assert.match(html, /MISSION 01 · EARTH DEPARTURE/);
assert.match(html, /LEAVE THE SOLAR SYSTEM/);
assert.match(html, /id="missionCompleteOverlay"/);
assert.match(html, /id="missionTwoButton"/);
assert.match(html, /MISSION 02 · ENDLESS/);
assert.match(html, /data-volume="musicVolume"/);
assert.match(html, /data-volume="sfxVolume"/);
assert.match(html, /id="testAudioButton"/);
assert.match(html, /id="audioStatus"[^>]*data-state="locked"/);
assert.match(html, /ENABLE \/ TEST AUDIO/);
assert.match(html, /data-setting="asteroids"/);
assert.match(html, /data-setting="music"/);
assert.match(html, /data-setting="soundFx"/);
assert.match(html, /data-setting="screenShake"/);
assert.match(html, /data-setting="weaponArrays"/);
assert.match(html, /id="activeWeaponName"/);
assert.match(html, /id="matterValue"/);
assert.match(html, /class="upgrade-market-note"/);
assert.match(html, /EVERY PRICE IS SHOWN ON ITS CARD/);
assert.doesNotMatch(html, /class="fabricator-grid"/);
assert.doesNotMatch(css, /\.fabricator-grid/);
assert.match(html, /id="shieldBar"/);
assert.match(html, /id="armorBar"/);
assert.match(html, /Damage order: shield → armour → hull/);
assert.match(html, /Mercury and Venus for a solar gravity assist/);
assert.ok(html.indexOf("ENERGY SHIELD") < html.indexOf("ARMOUR PLATING") && html.indexOf("ARMOUR PLATING") < html.indexOf("HULL INTEGRITY"), "defence HUD is ordered shield, armour, then hull");
assert.match(html, /id="upgradeList"/);
assert.match(html, /id="mobileFire"/);
assert.match(css, /@media \(max-width: 680px\)/);
assert.match(game, /event\.code === "Space"/);
assert.match(game, /event\.code === "Tab"/);
assert.match(game, /event\.code === "KeyO"/);
assert.match(game, /event\.code === "Escape"[\s\S]{0,280}setSettingsOpen\(true\)/);
assert.match(game, /state === "config"/);
assert.match(game, /state === "options"/);
assert.match(game, /event\.key === "Meta"/);
assert.match(game, /ship\.x = clamp/);
assert.match(game, /ship\.y = clamp/);
assert.match(game, /function spawnAsteroid/);
assert.match(game, /function createExplosion/);
assert.match(game, /function spawnUpgrade/);
assert.match(game, /spawnUpgrade\(asteroid\.x, asteroid\.y, "missile"\)/);
assert.match(game, /function applyUpgrade/);
assert.match(game, /function drawPowerUp/);
assert.match(game, /function chooseAsteroidComposition/);
assert.match(game, /function dropAsteroidResources/);
assert.match(game, /function drawResourceDrop/);
assert.match(game, /function spawnShootingStar/);
assert.match(game, /function drawShootingStar/);
assert.match(game, /const planetTypes = \[/);
assert.match(game, /function spawnPlanet/);
assert.match(game, /function drawPlanet/);
assert.match(game, /endGame\("PLANETARY IMPACT"\)/);
assert.match(game, /const solarBodyTypes = \{/);
assert.match(game, /earth: \{ id: "earth"/);
assert.match(game, /sun: \{ id: "sun"/);
assert.match(game, /mercury: \{ id: "mercury"/);
assert.match(game, /venus: \{ id: "venus"/);
assert.match(game, /mars: \{ id: "mars"/);
assert.match(game, /jupiter: \{ id: "jupiter"/);
assert.match(game, /saturn: \{ id: "saturn"/);
assert.match(game, /uranus: \{ id: "uranus"/);
assert.match(game, /neptune: \{ id: "neptune"/);
assert.match(game, /function drawSolarPlanet/);
assert.match(game, /function spawnSolarEquipment/);
assert.match(game, /function drawSpaceObject/);
assert.match(game, /AUTONOMOUS MINING RIG/);
assert.match(game, /ORBITAL SPACE TELESCOPE/);
assert.match(game, /function updateSolarMission/);
assert.match(game, /const GRAVITY_GATE_COUNT = 3/);
assert.match(game, /const WEAPONS_TRAINING_KILLS = 6/);
assert.match(game, /SOLAR SLINGSHOT/);
assert.match(game, /MERCURY FLYBY/);
assert.match(game, /VENUS GRAVITY ASSIST/);
assert.match(game, /function spawnGravityAssist/);
assert.match(game, /function updateGravityAssist/);
assert.match(game, /function completeGravityAssist/);
assert.match(game, /function failGravityAssist/);
assert.match(game, /function updateAssistFailure/);
assert.match(game, /function drawGravityAssistLane/);
assert.match(game, /function drawAssistFailureOverlay/);
assert.match(game, /state = "assistfailed"/);
assert.match(game, /assistFailureTimer = 3/);
assert.match(game, /GRAVITY ASSIST FAILED · TRAJECTORY LOST/);
assert.match(game, /FOLLOW THE ARROWS · PASS 3 GATES/);
assert.match(game, /type === "training"/);
assert.match(game, /type === "gate"/);
assert.match(game, /type === "assistSuccess"/);
assert.match(game, /type === "assistFail"/);
assert.match(game, /spawnAsteroid\(true\)/);
assert.match(game, /trainingTarget: training/);
assert.match(game, /beltTrainingKills = Math\.min/);
assert.match(game, /missionElapsed = 61\.9/);
assert.match(game, /function drawWeaponsTrainingOverlay/);
assert.match(game, /MARKED TARGETS DESTROYED/);
assert.match(game, /function startMissionOne/);
assert.match(game, /const LAUNCH_INTRO_DURATION = 8/);
assert.match(game, /const launchIntroCues = \[/);
assert.match(game, /state = "intro"/);
assert.match(game, /function updateLaunchIntro/);
assert.match(game, /function completeLaunchIntro/);
assert.match(game, /function drawLaunchIntro/);
assert.match(game, /function drawCinematicEarth/);
assert.match(game, /function drawPrelaunchVapour/);
assert.match(game, /function drawWaterDeluge/);
assert.match(game, /function drawCinematicSmoke/);
assert.match(game, /function drawCinematicRocket/);
assert.match(game, /function drawRocketBooster/);
assert.match(game, /function drawCinematicSpacecraft/);
assert.match(game, /drawShip\(renderX, renderY, renderScale, 0, 18 \* emerged/);
assert.match(game, /const handoff = introEase\(\(time - 7\.02\) \/ 0\.98\)/);
assert.doesNotMatch(game, /fillStyle = "#dffbff"[\s\S]{0,100}fillRect\(0, 0, width, height\)/);
assert.match(game, /"THE MISSION:"/);
assert.match(game, /"EXPLORE SPACE"/);
assert.match(game, /"T MINUS"/);
assert.match(game, /BOOSTER SEPARATION · CONFIRMED/);
assert.match(game, /FAIRING RELEASE · STARFALL DEPLOY/);
assert.match(game, /type === "countdown"/);
assert.match(game, /type === "vent"/);
assert.match(game, /type === "deluge"/);
assert.match(game, /type === "ignition"/);
assert.match(game, /type === "separation"/);
assert.match(game, /type === "reveal"/);
assert.match(game, /function completeMissionOne/);
assert.match(game, /function startMissionTwo/);
assert.match(game, /function clearSectorForMissionTwo/);
assert.match(game, /SOLAR_MISSION_DURATION = 128/);
assert.match(game, /mission === 2 && settings\.planets/);
assert.match(game, /function spawnAlienShip/);
assert.match(game, /function spawnSpaceStation/);
assert.match(game, /function fireEnemyWeapon/);
assert.match(game, /function damageHostile/);
assert.match(game, /function drawAlienShip/);
assert.match(game, /function drawSpaceStation/);
assert.match(game, /function drawEnemyProjectile/);
assert.match(game, /const weaponArrayTypes = \[/);
assert.match(game, /function spawnWeaponArray/);
assert.match(game, /function updateWeaponArray/);
assert.match(game, /function fireArrayMissile/);
assert.match(game, /function drawWeaponArrayTargeting/);
assert.match(game, /function drawWeaponArray/);
assert.match(game, /array\.lockProgress >= 1/);
assert.match(game, /arrayMissile: true/);
assert.match(game, /sourceKind: "array"/);
assert.match(game, /cloakTimer > 0[\s\S]{0,180}array\.lockProgress = Math\.max/);
assert.match(game, /defense: "fortified"/);
assert.match(game, /function acquireMissileTarget/);
assert.match(game, /hostile\.patrolPhase = 0/);
assert.match(game, /Math\.sin\(hostile\.patrolPhase\)/);
assert.doesNotMatch(game, /Math\.sin\(hostile\.phase \* frequency\)/);
assert.match(game, /projectile\.targetClock = 0\.12/);
assert.match(game, /const PERFORMANCE_LIMITS = Object\.freeze/);
assert.match(game, /playerProjectiles: 240/);
assert.match(game, /particles: 600/);
assert.match(game, /function addPlayerProjectile/);
assert.match(game, /function addEnemyProjectile/);
assert.match(game, /function pushParticle/);
assert.match(game, /function pushShockwave/);
assert.match(game, /const trailQuality = clamp/);
assert.match(game, /function drawProjectile\(projectile, simplified = false\)/);
assert.match(game, /const SFX_COOLDOWNS = Object\.freeze/);
assert.match(game, /const dynamicCooldown = cooldown/);
assert.doesNotMatch(game, /for \(const asteroid of \[\.\.\.asteroids\]/);
assert.doesNotMatch(game, /for \(const hostile of \[\.\.\.alienShips/);
assert.doesNotMatch(game, /for \(const candidate of \[\.\.\.asteroids/);
assert.match(game, /starfall-settings-v1/);
assert.match(game, /function setFeatureSetting/);
assert.match(game, /function renderMusicTrack/);
assert.match(game, /const trackId = mission === 1 \? "solar" : "deep"/);
assert.match(game, /audioContext\.createBufferSource\(\)/);
assert.match(game, /source\.loop = true/);
assert.match(game, /const bpm = solar \? 96 : 74/);
assert.match(game, /voice === "pad"/);
assert.match(game, /voice === "bass"/);
assert.match(game, /voice === "glass"/);
assert.match(game, /function sfxVoice/);
assert.match(game, /function sfxNoise/);
assert.match(game, /type === "missile"[\s\S]{0,420}sfxNoise/);
assert.match(game, /type === "explosion"[\s\S]{0,420}sfxVoice/);
assert.match(game, /starfall-audio-engine-v2/);
assert.match(game, /function refreshAudioStatus/);
assert.match(game, /function updateMusicState/);
assert.match(game, /function setVolumeSetting/);
assert.match(game, /sfxBus\.gain\.setValueAtTime/);
assert.match(game, /playTone\("launch"\)/);
assert.match(game, /playTone\("complete"\)/);
assert.match(game, /function fabricate/);
assert.match(game, /upgrades\.regeneration > 0/);
assert.match(game, /let armor = 0/);
assert.match(game, /if \(remainingDamage > 0 && armor > 0\)/);
assert.match(game, /shield = Math\.min\(shieldMax, shield \+ \(3\.5 \+ upgrades\.shieldOvercharge/);
assert.match(game, /function ricochetLaser/);
assert.match(game, /ricochetRemaining: upgrades\.ricochet/);
assert.match(game, /75 \+ upgrades\.magnet \* 115/);
assert.match(game, /90 \+ upgrades\.magnet \* 135/);
assert.match(game, /cloakTimer = Math\.max\(cloakTimer, upgrades\.cloak \* 10\)/);
assert.match(game, /cloakTimer <= 0 && hostile\.life > 0/);
assert.match(game, /rapidFireTimer > 0 \? 0\.3 : 1/);
assert.match(game, /rapidFireTimer = Math\.min\(30, rapidFireTimer \+ 8\)/);
assert.match(game, /radius: 17 \+ scalableLevel \* 1\.7/);
assert.match(game, /const upgradeCatalog = \[/);
assert.match(game, /function upgradeIllustration/);
assert.match(game, /data-fabricate="\$\{item\.type\}" class="upgrade-card/);
assert.match(game, /FABRICATE · \$\{cost\} MU/);
assert.match(game, /SELECT TO BUILD/);
assert.match(game, /type: "shieldRepair"/);
assert.match(game, /type: "armorRepair"/);
assert.match(game, /type: "hullRepair"/);
assert.match(game, /missile: 18, plasma: 22, railgun: 26/);
assert.match(game, /ui\.upgradeList\.addEventListener\("click"/);
assert.match(game, /class="upgrade-picture"/);
assert.match(game, /class="upgrade-group-title"/);
assert.match(game, /<svg viewBox="0 0 80 72"/);
assert.match(game, /type: "plasma"/);
assert.match(game, /type: "railgun"/);
assert.match(game, /unlockedWeapons = new Set\(\["laser"\]\)/);
assert.doesNotMatch(game, /asteroid\.y - asteroid\.radius > height[\s\S]{0,160}damageShip/);
assert.match(css, /\.radar-dot\.planet-dot/);
assert.match(css, /\.radar-dot\.hostile-dot/);
assert.match(css, /\.radar-dot\.hostile-dot\.array-dot/);
assert.match(css, /\.upgrade-card\.installed/);
assert.match(css, /\.upgrade-card\.affordable/);
assert.match(css, /\.upgrade-purchase/);
assert.match(css, /\.upgrade-market-note/);
assert.match(css, /\.upgrade-picture svg/);
assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(css, /\.setting-toggle\.enabled/);
assert.match(css, /\.mission-banner/);
assert.match(css, /\.story-copy/);
assert.match(css, /body\.cinematic-active \.hud/);
assert.match(css, /\.volume-control/);
assert.match(favicon, /<svg[^>]+viewBox="0 0 64 64"/);
assert.match(game, /localStorage\.setItem\("starfall-high-score"/);

console.log("Static game checks passed.");
